### PR TITLE
Julia one fixes

### PR DESCRIPTION
**Pull request by jstrube**
Changes for updating to julia-1 and for expanding the gcc versions.

### CODE REVIEW

**Comment by bicycle1885** [comment]
I've just read this announcement (https://discourse.julialang.org/t/binarybuilder-and-gcc-multi-versioning/15314), and I wonder if this GCC expansion is required for ZlibBuilder. Since zlib is not linked against libgfortran, the binary compatibility issue will not happen? I'm sorry for asking this after you do some updates.

**Comment by jstrube** [comment]
I'm not entirely sure, but I think if you don't specify it, you will always
get the gcc-4 version, which is fine for zlib, but I was using some other
lib, which needed to specify the gcc version, and for the gcc-7 version, I
got a complaint that zlib is not supported in this version.
So, I _think_ that specifying the version is always correct, but I'm not
entirely sure. Maybe I was doing something wrong in my setup when I tried.
We should ask @staticfloat to clarify if versions are always correct, or if
mixing versioned and unversioned builders is OK.

**Comment by jstrube** [comment]
Well, so to give you another data point: 
without this, I'm getting 
```
cd /workspace/srcdir/build/lcio && /usr/bin/cmake -E cmake_link_script CMakeFiles/bin_stdhepjob.dir/link.txt --verbose=ON
/opt/x86_64-linux-gnu/bin/x86_64-linux-gnu-g++ --sysroot=/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/  -fdiagnostics-color=auto -std=c++11 -Wl,-no-undefined -Wno-non-virtual-dtor -Wuninitialized -Wno-long-long -pedantic -Weffc++ -Wshadow -Wextra -Wall  -O2 -g -DNDEBUG  -rdynamic CMakeFiles/bin_stdhepjob.dir/src/EXAMPLE/stdhepjob.cc.o  -o ../bin/stdhepjob -Wl,-rpath,/workspace/srcdir/build/lib:/workspace/destdir/lib: ../lib/liblcio.so.2.12.1 ../lib/libsio.so.2.12.1 /workspace/destdir/lib/libz.so 
/workspace/destdir/lib/libz.so: undefined reference to `memcpy@GLIBC_2.14'
```
for my LCIOBuilder repo. Since LCIO is C++, it depends on the gcc ABI, if I understand @staticfloat correctly, so I don't have a choice in my case. But, I'm really not an expert in gcc and linkers. All I know is that this PR fixes my problem.

**Comment by staticfloat** [comment]
Unfortunately, the `@GLIBC_2.14` error is unrelated, and is my fault.  I apologize.  Here's what happened:

I upgraded the version of `glibc` being bundled within the rootfs from `2.12.2` to `2.17`, because I was having trouble building the older version with all the different versions of GCC as part of the new rootfs I was putting together.  I publish that new rootfs and a new version of `libz` was distributed that used it.  This caused that version of `libz` to depend upon a `memcpy` symbol that is versioned at `GLIBC_2.14`, meaning that something about `memcpy`'s behavior changed in the `2.14` release of glibc, which is included for backwards-compatibility purposes in `2.17`.  However, I got some complaints from users who run on very old Linux systems that only provide `glibc` `2.12` that they could no longer run `BinaryBuilder` binaries, so I went back and fixed the issues with `2.12.2` and reverted back to that version for the rootfs.  This means that when you try to compile your `lcio` binary, your GCC executable tries to link your binary, `libz` and `glibc` `2.12.2` all together, and fails, because `libz` was built against `2.17`.

The solution is simple, luckily.  We just need to get Kenta to build another version of `libz` with the latest `BinaryBuilder`, and it will link against `glibc` `2.12.2`, you'll use the new URL as your dependency, and all will be right within the world.

**Comment by jstrube** [comment]
Thanks for the update. Yes, unfortunately most of high energy physics is still running Enterprise Linux 6 and derivatives, not sure what the glibc version is on those, but it's _old_. This fix is much appreciated.

**Comment by staticfloat** [comment]
While BB does work best on 1.0 nowadays, the rest (installing the latest `master` of BinaryProvider and using GCC version expansion) is unneeded.  However, Kenta, if I could ask you to tag a new version the most important part is that your generated `build.jl` file use `choose_download()` to get the right version to download.  This will happen automatically when you tag a new release.

**Comment by TransGirlCodes** [comment]
Can this get merged?

**Comment by jstrube** [comment]
I'm just now building against the more basic gcc version again (without the specific abi tag). Seems to work for me with the new BinaryBuilder docker.
See binaries [here](https://github.com/jstrube/ZlibBuilder/releases/tag/v1.4). Will update PR and remove repo once PR is merged.

**Comment by bicycle1885** [comment]
`expand_gcc_versions` will not be required for now, so I've merged #9 instead of this.

**Pull request closed without merging**
